### ISSUE TITLE
DPI-NET can't download submodule.

### ISSUE THREAD

**Issue by zloyaloha** [YunzhuLi/DPI-Net#6]
I try to install repo and clone PyFlex submodule like in instruction, but always get mistake

Submodule 'PyFleX' ([git@github.com](mailto:git@github.com):YunzhuLi/PyFleX.git) registered for path 'PyFleX'
Cloning into '/content/DPI-Net/PyFleX'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of '[git@github.com](mailto:git@github.com):YunzhuLi/PyFleX.git' into submodule path '/content/DPI-Net/PyFleX' failed
Failed to clone 'PyFleX'. Retry scheduled
Cloning into '/content/DPI-Net/PyFleX'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of '[git@github.com](mailto:git@github.com):YunzhuLi/PyFleX.git' into submodule path '/content/DPI-Net/PyFleX' failed
Failed to clone 'PyFleX' a second time, aborting

**Comment by zloyaloha** [comment]
Okey, I solved problem with installation, but after testing PyFlex i got 

/content/DPI-Net/PyFleX/bindings/examples
Traceback (most recent call last):
  File "/content/DPI-Net/PyFleX/bindings/examples/test_FluidFall.py", line 3, in <module>
    import pyflex
ImportError: /content/DPI-Net/PyFleX/bindings/build/pyflex.cpython-39-x86_64-linux-gnu.so: undefined symbol: __powf_finite

**Comment by HaronW** [comment]
> Okey, I solved problem with installation, but after testing PyFlex i got
> 
> /content/DPI-Net/PyFleX/bindings/examples Traceback (most recent call last): File "/content/DPI-Net/PyFleX/bindings/examples/test_FluidFall.py", line 3, in import pyflex ImportError: /content/DPI-Net/PyFleX/bindings/build/pyflex.cpython-39-x86_64-linux-gnu.so: undefined symbol: __powf_finite


The same problem, did you solve it?
